spring.application.name=springBoot
server.port = 9090

#MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/MovieDB?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=system
#spring.jpa.hibernate.ddl-auto=update

#postgres
spring.datasource.url=jdbc:postgresql://ep-shiny-hat-a58evpsg-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MA7JqDC3RIbS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5


